// Generated by the API build step in Vercel buildCommand.
// @ts-ignore File exists after `pnpm --filter @workspace/api-server build`.
import app from "../artifacts/api-server/dist/app.mjs";

export default app;